# <xpfo{ .ProjectName }xpfo>

Generated by `akali`.

## Run

```bash
go mod tidy
go run . -c ./config.yaml
```

## Quality Checks

```bash
go test ./...
go vet ./...
go build ./...
```

## Docker

```bash
docker build -t <xpfo{ .ProjectName }xpfo>:local .
docker run --rm -p 17878:17878 <xpfo{ .ProjectName }xpfo>:local
```

## Endpoints

- `GET /ping`
- `GET /health`
- `GET /version`
<xpfo{ if .EnableMetrics }xpfo>
- `GET /metrics`
<xpfo{ end }xpfo>
<xpfo{ if .EnableSwagger }xpfo>
- `GET /swagger/index.html` (debug mode only)
<xpfo{ end }xpfo>
<xpfo{ if .EnableAuth }xpfo>
- `GET /api/v1/secure/ping` (JWT required)
<xpfo{ end }xpfo>
